import ephem
import math
from PIL import Image, ImageDraw, ImageFont
from datetime import datetime

def generate_star_map(lat, lon, user_name="Исследователь"):
    # 1. Настройки размера холста
    WIDTH, HEIGHT = 800, 800
    CENTER = (400, 400)
    RADIUS = 350
    
    # 2. Создаем изображение (глубокий космический цвет)
    # Используем темно-синий RGB (5, 10, 35)
    img = Image.new('RGB', (WIDTH, HEIGHT), (5, 10, 35))
    draw = ImageDraw.Draw(img)

    # 3. Настройка наблюдателя через библиотеку ephem
    obs = ephem.Observer()
    obs.lat = str(lat)
    obs.lon = str(lon)
    obs.date = datetime.utcnow()
    obs.pressure = 0  # Игнорируем искажение атмосферы для четкости

    # 4. Рисуем круг горизонта (граница неба)
    draw.ellipse([CENTER[0]-RADIUS, CENTER[1]-RADIUS, 
                  CENTER[0]+RADIUS, CENTER[1]+RADIUS], 
                 outline=(40, 60, 120), width=4)

    # 5. База ярких звезд (Название, Координаты, Магнитуда)
    # Мы берем самые узнаваемые звезды, чтобы карта была красивой
    stars_data = [
        "Sirius,f|S|A1,6:45:08.9,-16:42:58,1.46,2000",
        "Vega,f|S|A0,18:36:56.3,38:47:01,0.03,2000",
        "Polaris,f|S|F7,2:31:48.7,89:15:51,1.97,2000",
        "Betelgeuse,f|S|M1,5:55:10.3,7:24:25,0.45,2000",
        "Rigel,f|S|B8,5:14:32.3,-8:12:06,0.12,2000",
        "Capella,f|S|G5,5:16:41.4,45:59:53,0.08,2000",
        "Arcturus,f|S|K1,14:15:39.7,19:10:57,-0.05,2000",
        "Altair,f|S|A7,19:50:47.0,8:52:06,0.77,2000",
        "Deneb,f|S|A2,20:41:25.9,45:16:49,1.25,2000"
    ]

    for s_entry in stars_data:
        star = ephem.readdb(s_entry)
        star.compute(obs)
        
        # Рисуем звезду только если она выше горизонта (alt > 0)
        if star.alt > 0:
            # Математическая проекция сферы на плоскость (x, y)
            # r — расстояние от центра (чем выше звезда, тем ближе к центру)
            r = RADIUS * (1 - (float(star.alt) / (math.pi / 2)))
            # angle — азимут (куда смотреть: север, юг и т.д.)
            angle = float(star.az) - math.pi / 2
            
            x = CENTER[0] + r * math.cos(angle)
            y = CENTER[1] + r * math.sin(angle)
            
            # Определяем размер точки в зависимости от яркости звезды
            size = 2
            if float(star.mag) < 0.5: size = 4
            elif float(star.mag) < 1.5: size = 3
            
            # Рисуем саму звезду
            draw.ellipse([x-size, y-size, x+size, y+size], fill='white')
            
            # Подписываем названия самых ярких звезд
            if float(star.mag) < 1.0:
                draw.text((x + 5, y + 5), star.name, fill=(200, 200, 200))

    # 6. Добавляем авторскую подпись и инфо
    title_text = f"STAR MAP FOR: {user_name.upper()}"
    date_text = datetime.now().strftime("%d.%m.%Y %H:%M")
    
    draw.text((20, 20), title_text, fill=(255, 215, 0)) # Золотой цвет
    draw.text((20, 45), f"COORDINATES: {lat:.2f}, {lon:.2f}", fill=(150, 150, 150))
    draw.text((20, 750), f"GENERATED BY MARTIN BOT | {date_text}", fill=(100, 100, 100))

    # 7. Сохраняем и отдаем путь к файлу
    output_path = "user_sky.png"
    img.save(output_path)
    return output_path
