name: asteroid_bot.py

on:
  schedule:
    # Запуск ежедневно в 11:00 UTC (14:00 по МСК)
    - cron: '0 11 * * *'
  workflow_dispatch:      # Кнопка ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write # Нужно для сохранения last_asteroid_id.txt

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests

      - name: Run asteroid_bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
        run: python asteroid_bot.py

      - name: Save memory
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add last_asteroid_id.txt
          git commit -m "Update asteroid memory: $(date)" || echo "No changes"
          git pull --rebase origin main
          git push origin main
