name: asteroid_bot.py
on:
  schedule:
    - cron: '0 12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install requests
      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
        run: python asteroid_bot.py
      - name: Save memory
        run: |
          git config --global user.name "GitHub Bot"
          git config --global user.email "bot@github.com"
          # Создаем файл если его нет, чтобы git add не падал
          if [ ! -f last_asteroid_id.txt ]; then touch last_asteroid_id.txt; fi
          git add last_asteroid_id.txt
          git commit -m "Update memory" || echo "No changes"
          git push
