name: Space Automation

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  run-bots:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install requests deep_translator
      - name: Start Bots
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
        run: |
          python bot_launch.py
      - name: Save Memory
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add db_launch.txt sent_radar_lives.txt || echo "No files"
          git commit -m "Update DB" || echo "No changes"
          git push
