name: Bot Launch Notifier

on:
  schedule:
    - cron: '0 * * * *' # Раз в час, чтобы не тратить лимиты API часто
  workflow_dispatch: # Позволяет запустить вручную кнопкой

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Важно для записи в db_launch.txt

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests deep_translator

      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
        run: python bot_launch.py

      - name: Commit and Push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 Память обновлена: db_launch.txt"
          file_pattern: 'db_launch.txt'
