name: Space Radar & Daily Post

on:
  schedule:
    # Запуск каждые 15 минут (память теперь защитит от спама)
    - cron: '*/15 * * * *'
  workflow_dispatch:

permissions:
  contents: write  # Разрешаем сохранять файл с датой

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests deep_translator pyTelegramBotAPI google-api-python-client

      - name: Run Space Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          CHANNEL_NAME: ${{ secrets.CHANNEL_NAME }}
        run: python video_bot.py

      - name: Save memory (Commit date)
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add last_video_date.txt || true
          git commit -m "Update last video date" || true
          git push
