name: NASA Daily Content

on:
  schedule:
    - cron: '0 9 * * *'  # 12:00 по твоему времени (фото)
    - cron: '0 15 * * *' # 18:00 по твоему времени (видео)
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      
      # Если сейчас 9:00 UTC — шлем фото
      - name: Post Photo
        if: github.event.schedule == '0 9 * * *' || github.event_name == 'workflow_dispatch'
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: python cosmos_photo.py image

      # Если сейчас 15:00 UTC — шлем видео
      - name: Post Video
        if: github.event.schedule == '0 15 * * *'
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        run: python cosmos_photo.py video
