name: space_radar.py

on:
  schedule:
    - cron: '0 */3 * * *' # Каждые 3 часа
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install requests deep_translator
      - run: python space_radar.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}

      - name: Save memory
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add sent_radar_lives.txt
          git commit -m "Update radar memory" || echo "No changes"
          git pull --rebase origin main
          git push
