name: Sync to Hugging Face Spaces
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"

          git checkout --orphan deploy-branch
          git rm -rf . --cached

          # ДОБАВИЛИ README.md В СПИСОК НИЖЕ
          git add main.py draw_map.py constellations.json requirements.txt Dockerfile README.md

          git commit -m "Deploy Martin: Added README config"
          git push --force https://Fomich85:$HF_TOKEN@huggingface.co/spaces/Fomich85/martin-star-bot deploy-branch:main
