name: video_bot.py

on:
  schedule:
    - cron: '*/15 * * * *' # Проверка каждые 15 минут
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests deep_translator

      - name: Run video_bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
        run: python video_bot.py

      - name: Save memory
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          touch last_video_date.txt # Создает файл, если его не существует
          git add last_video_date.txt
          git commit -m "Update video memory: $(date)" || echo "No changes to commit"
          git pull --rebase origin main
          git push origin main
