name: video_bot.py

on:
  schedule:
    # Запуск каждые 15 минут для проверки обновлений
    - cron: '*/15 * * * *'
  workflow_dispatch:      # Кнопка для ручного запуска

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write # Разрешение на изменение файлов в репозитории

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install requests deep_translator

      - name: Run video_bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          NASA_API_KEY: ${{ secrets.NASA_API_KEY }}
          CHANNEL_NAME: ${{ secrets.CHANNEL_NAME }}
        run: python video_bot.py

      - name: Save memory
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          # Добавляем файл памяти в индекс
          git add last_video_date.txt
          # Фиксируем изменения
          git commit -m "Update last video date: $(date)" || echo "No changes to commit"
          # Синхронизация и пуш
          git pull --rebase origin main
          git push origin main
